### ISSUE TITLE
Formulário da Ficha

### ISSUE THREAD

**Issue by RogerioKlein** [GutoVargas/Krodtlott#1]
Incluir um formulário em HTML para inserir os dados da Ficha do Personagem.
@GutoVargas 
<img width="581" alt="ficha 1" src="https://user-images.githubusercontent.com/64874964/172864045-ca3daf58-8a19-4fa0-9560-23e1fbb3b39a.png">

**Comment by GutoVargas** [comment]
Vai demorar só um mês mas dá pra fazer hahaha
